#
# Leviathan Docker Container Network Orchestrator
#
#
# docker run -v /run:/run -v /var:/host/var -v /proc:/host/proc 
#            --net=host --privileged=true -i -t ivanos/core:priv-1 
#
FROM ivanos/core:devel-erl

MAINTAINER IvanOS version: 0.1

RUN wget -qO- https://get.docker.com/ | sh 
