#
# Leviathan Docker Container Network Orchestrator
#
FROM ubuntu:14.04

MAINTAINER IvanOS version: 0.1

RUN apt-get update && \
    apt-get install -y gcc && \
    apt-get install -y make && \
    apt-get install -y binutils && \
    apt-get install -y autoconf && \ 
    apt-get install -y ncurses && \ 
    apt-get install -y ncurses-dev  && \ 
    apt-get install -y libpam0g-dev  && \ 
    apt-get install -y libpam4j-java && \
    apt-get install -y openssl-dev && \
    apt-get install -y libssl-dev && \
    apt-get install -y default-jdk && \
    apt-get install -y g++ && \
    apt-get install -y unixodbc-dev && \ 
    apt-get install -y fop && \
    apt-get install -y xsltproc  && \
    apt-get install -y xmllint && \
    apt-get install -y libxml2-utils && \ 
    apt-get install -y ruby-dev


CMD /usr/bin/bash
