#
# Leviathan Docker Container Network Orchestrator
#
FROM ubuntu:14.04

MAINTAINER IvanOS version: 0.1

RUN apt-get update && \
    apt-get install gcc && \
    apt-get install make && \
    apt-get install binutils && \
    apt-get install autoconf && \ 
    apt-get install ncurses && \ 
    apt-get install ncurses-dev  && \ 
    apt-get install libpam0g-dev  && \ 
    apt-get install libpam4j-java && \
    apt-get install openssl-dev && \
    apt-get install libssl-dev && \
    apt-get install default-jdk && \
    apt-get install g++ && \
    apt-get install unixodbc-dev && \ 
    apt-get install fop && \
    apt-get install xsltproc  && \
    apt-get install xmllint && \
    apt-get install libxml2-utils && \ 
    apt-get install ruby-devapt-get install 


CMD /usr/bin/bash
